import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { FDTD3D } from './fdtd-3d.js';

const $=s=>document.querySelector(s),canvas=$('#field-3d'),tools=$('#tools-3d'),readout=$('#readout-3d'),engineSelect=$('#engine');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050911);scene.fog=new THREE.FogExp2(0x050911,.018);
const camera=new THREE.PerspectiveCamera(48,1,.1,250);camera.position.set(20,17,24);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.08;controls.target.set(0,3,0);controls.maxPolarAngle=Math.PI*.49;controls.minDistance=8;controls.maxDistance=70;
scene.add(new THREE.HemisphereLight(0x9adfff,0x07101c,1.8));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(-12,22,10);scene.add(key);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(42,30),new THREE.MeshStandardMaterial({color:0x0a1522,roughness:.9,metalness:.05}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(42,42,0x28506a,0x142738);grid.position.y=.01;scene.add(grid);
const objects=[],barriers=[],links=new THREE.Group(),solver=new FDTD3D();scene.add(links);
const colors={source:0xfb7185,probe:0x67e8f9,victim:0xfbbf24,shield:0x94a3b8,absorber:0x34d399};let selected=null,dragging=false,time=0,last=performance.now(),frameCount=0;
function material(color,opacity=1){return new THREE.MeshStandardMaterial({color,roughness:.42,metalness:.22,transparent:opacity<1,opacity})}
function rebuildMaterials(){solver.clearMaterials();for(const obstacle of barriers){const box=new THREE.Box3().setFromObject(obstacle);solver.rasterBox(box.min,box.max,obstacle.userData.type)}}
function addObject(type,position){let mesh;if(type==='source'){mesh=new THREE.Mesh(new THREE.SphereGeometry(.65,24,16),material(colors[type]));mesh.position.y=1.5;const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.08,10,40),new THREE.MeshBasicMaterial({color:colors[type]}));ring.rotation.x=Math.PI/2;mesh.add(ring);const glow=new THREE.PointLight(colors[type],3.5,8,2);mesh.add(glow)}else if(type==='probe'||type==='victim'){mesh=new THREE.Mesh(new THREE.CylinderGeometry(.28,.45,1.5,18),material(colors[type]));mesh.position.y=.75}else{mesh=new THREE.Mesh(new THREE.BoxGeometry(type==='shield'?1:2.2,6,type==='shield'?11:8),material(colors[type],type==='absorber'?.72:.9));mesh.position.y=3;mesh.userData.attenuation=type==='shield'?70:18;barriers.push(mesh)}mesh.position.x+=position.x;mesh.position.z+=position.z;mesh.userData.type=type;mesh.userData.history=[];objects.push(mesh);scene.add(mesh);selected=mesh;rebuildMaterials();return mesh}
function clear3D(){for(const o of objects)scene.remove(o);objects.length=barriers.length=0;links.clear();solver.clear();solver.clearMaterials()}
function reset3D(){time=0;solver.clear();rebuildMaterials();for(const o of objects){o.userData.history=[];o.userData.latest=null}updateLinks();updateVolume();updateReadout()}
function loadDefault(){clear3D();addObject('source',new THREE.Vector3(-13,0,0));addObject('probe',new THREE.Vector3(-5,0,-5));addObject('victim',new THREE.Vector3(13,0,0));const upper=addObject('shield',new THREE.Vector3(0,0,-7));upper.scale.z=.48;const lower=addObject('shield',new THREE.Vector3(0,0,7));lower.scale.z=.48;addObject('absorber',new THREE.Vector3(7,0,-7));selected=objects[0]}
const scenarios={
  room:{name:'Sala com abertura',desc:'Fonte e vítima separadas por blindagem parcial.',build:loadDefault},
  free:{name:'Espaço livre',desc:'Compare 1/r em sondas a distâncias diferentes.',build(){clear3D();addObject('source',new THREE.Vector3(-14,0,0));addObject('probe',new THREE.Vector3(-7,0,0));addObject('probe',new THREE.Vector3(0,0,0));addObject('victim',new THREE.Vector3(12,0,0))}},
  shielding:{name:'Parede blindada',desc:'Observe a perda de inserção através de uma barreira PEC completa.',build(){clear3D();addObject('source',new THREE.Vector3(-13,0,0));addObject('probe',new THREE.Vector3(-5,0,0));const wall=addObject('shield',new THREE.Vector3(0,0,0));wall.scale.set(1,3,2.8);wall.position.y=6;addObject('victim',new THREE.Vector3(12,0,0));rebuildMaterials()}},
  absorber:{name:'Tratamento absorvedor',desc:'Compare caminhos com blindagem e material absorvedor.',build(){clear3D();addObject('source',new THREE.Vector3(-13,0,-5));addObject('absorber',new THREE.Vector3(0,0,-5));addObject('probe',new THREE.Vector3(12,0,-5));addObject('source',new THREE.Vector3(-13,0,7));addObject('victim',new THREE.Vector3(12,0,7))}}
};
function sources(){return objects.filter(o=>o.userData.type==='source')}function receivers(){return objects.filter(o=>o.userData.type==='probe'||o.userData.type==='victim')}
function fieldAt(point){return{...solver.sample(point),loss:0}}
function pathBlocked(origin,target){const direction=target.clone().sub(origin),distance=direction.length(),ray=new THREE.Ray(origin,direction.normalize());return barriers.some(obstacle=>obstacle.userData.type==='shield'&&(()=>{const hit=ray.intersectBox(new THREE.Box3().setFromObject(obstacle),new THREE.Vector3());return hit&&hit.distanceTo(origin)<distance})())}
function updateLinks(){links.clear();const source=sources()[0];if(!source)return;const origin=source.getWorldPosition(new THREE.Vector3());for(const receiver of receivers()){const target=receiver.getWorldPosition(new THREE.Vector3()),result=fieldAt(target),blocked=pathBlocked(origin,target),geometry=new THREE.BufferGeometry().setFromPoints([origin,target]),safe=receiver.userData.type!=='victim'||Math.abs(result.value)<.08,line=new THREE.Line(geometry,new THREE.LineDashedMaterial({color:blocked?0xfb7185:safe?0x34d399:0xfbbf24,dashSize:.45,gapSize:.25,transparent:true,opacity:blocked?.35:.8}));line.computeLineDistances();links.add(line);receiver.userData.latest=result;receiver.userData.history.push(result.value);if(receiver.userData.history.length>500)receiver.userData.history.shift()}}
const samplePositions=[],sampleColors=[],sampleGeometry=new THREE.BufferGeometry();for(let y=.5;y<=10.5;y+=1)for(let z=-14;z<=14;z+=1)for(let x=-20;x<=20;x+=1){samplePositions.push(x,y,z);sampleColors.push(0,0,0)}sampleGeometry.setAttribute('position',new THREE.Float32BufferAttribute(samplePositions,3));sampleGeometry.setAttribute('color',new THREE.Float32BufferAttribute(sampleColors,3));const volume=new THREE.Points(sampleGeometry,new THREE.PointsMaterial({size:.16,vertexColors:true,transparent:true,opacity:.94,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(volume);const sampleValues=new Float32Array(samplePositions.length/3),samplePhase=new Float32Array(samplePositions.length/3);
function updateVolume(){const position=sampleGeometry.attributes.position,color=sampleGeometry.attributes.color,positive=new THREE.Color(0x22d3ee),negative=new THREE.Color(0xfb7185),mix=new THREE.Color(),point=new THREE.Vector3();let peak=1e-7;for(let i=0;i<position.count;i++){point.set(position.getX(i),position.getY(i),position.getZ(i));const result=fieldAt(point);sampleValues[i]=result.value;samplePhase[i]=result.ez;peak=Math.max(peak,result.value)}const reference=Math.max(peak*.06,2e-5);for(let i=0;i<position.count;i++){const value=sampleValues[i],strength=value<2e-6?0:Math.min(1,Math.sqrt(value/reference));mix.copy(samplePhase[i]>=0?positive:negative);color.setXYZ(i,mix.r*strength,mix.g*strength,mix.b*strength)}color.needsUpdate=true}
function updateReadout(){const probes=receivers(),source=sources()[0];readout.innerHTML=`<strong>FDTD VETORIAL 3D</strong><br>Grade Yee ${solver.nx}×${solver.ny}×${solver.nz} · 6 componentes E/H<br>PEC volumétrico · meio dissipativo · contorno absorvente<br>Fonte: ${source?'ativa':'ausente'} · barreiras: ${barriers.length}<br><span class="wave-hint">▶ Executar avança o campo eletromagnético</span><br><br>${probes.map((p,i)=>{const r=p.userData.latest||{value:0},peak=Math.max(0,...p.userData.history.map(Math.abs)),victim=p.userData.type==='victim';return `<span class="${victim&&peak>.08?'warn':'ok'}">${victim?'VÍTIMA':'SONDA'} ${i+1}: |E|=${r.value.toFixed(4)} · pico=${peak.toFixed(4)}</span>`}).join('<br>')||'Adicione uma sonda ou vítima.'}`;$('#method-label').textContent='FDTD vetorial 3D';$('#step-label').textContent=`PASSO ${solver.time}`}
function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width)),h=Math.max(1,Math.floor(r.height));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function active(){return engineSelect.value==='emc3d'}function setMode(){const on=active();canvas.hidden=!on;$('#field').hidden=on;tools.hidden=!on;readout.hidden=!on;document.body.classList.toggle('mode-3d',on);if(on){resize();updateLinks();updateReadout()}}
engineSelect.addEventListener('change',setMode);window.addEventListener('resize',()=>active()&&resize());
tools.querySelectorAll('[data-add-3d]').forEach(button=>button.onclick=()=>{const count=objects.length,angle=count*2.1;addObject(button.dataset.add3d,new THREE.Vector3(Math.cos(angle)*8,0,Math.sin(angle)*7));updateLinks();updateReadout()});$('#reset-3d-view').onclick=()=>{camera.position.set(20,17,24);controls.target.set(0,3,0);controls.update()};
$('#scene-3d').onchange=e=>{scenarios[e.target.value].build();reset3D()};
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);function pointerRay(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera)}canvas.onpointerdown=e=>{pointerRay(e);const hit=raycaster.intersectObjects(objects,false)[0];if(hit){selected=hit.object;dragging=true;controls.enabled=false;canvas.setPointerCapture(e.pointerId)}};canvas.onpointermove=e=>{if(!dragging||!selected)return;pointerRay(e);const point=new THREE.Vector3();if(raycaster.ray.intersectPlane(ground,point)){selected.position.x=THREE.MathUtils.clamp(point.x,-19,19);selected.position.z=THREE.MathUtils.clamp(point.z,-13,13);updateLinks()}};canvas.onpointerup=e=>{dragging=false;controls.enabled=true;rebuildMaterials();canvas.releasePointerCapture?.(e.pointerId)};
window.addEventListener('keydown',e=>{if(!active()||e.key!=='Delete'||!selected)return;scene.remove(selected);objects.splice(objects.indexOf(selected),1);const bi=barriers.indexOf(selected);if(bi>=0)barriers.splice(bi,1);selected=null;updateLinks();updateReadout()});

const originalExport=$('#export').onclick;
window.addEventListener('emc3d:load',event=>{const key=event.detail;if(!scenarios[key])return;$('#scene-3d').value=key;scenarios[key].build();reset3D()});
$('#reset').addEventListener('click',()=>{if(active())reset3D()});
$('#clear').addEventListener('click',()=>{if(active()){clear3D();selected=null;updateReadout()}});
$('#export').onclick=function(){if(!active())return originalExport.call(this);const data=receivers();if(!data.length){alert('Adicione sondas ou vítimas para exportar dados');return}const rows=Math.max(...data.map(o=>o.userData.history.length));let csv='amostra,'+data.map((o,i)=>`${o.userData.type}_${i+1}_V_m`).join(',')+'\n';for(let i=0;i<rows;i++)csv+=i+','+data.map(o=>(o.userData.history[i]??'')).join(',')+'\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`emc-3d-${Date.now()}.csv`;a.click();URL.revokeObjectURL(url)};
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(active()){if($('#play').textContent.includes('Pausar')){time+=dt;solver.step(sources().map(o=>o.position),2)}controls.update();if(++frameCount%3===0){updateLinks();updateVolume();updateReadout()}renderer.render(scene,camera)}requestAnimationFrame(loop)}
loadDefault();setMode();requestAnimationFrame(loop);
