import { Sim } from "../core/sim-base.js";
import { PI, sin, cos, sqrt, abs, min, max, MU0 } from "../core/math.js";
import { W, H } from "../core/canvas.js";

export class BiotSavartSim extends Sim {
	constructor(){super("Biot–Savart Numérico","∮");this.geometry="wire";this.current=3;this.size=20;this.distance=10;this.elements=40;this.showElements=true;this.hint="Aumente os segmentos e observe a soma de dB convergir"}
	buildControls(el){el.innerHTML=`<h3><span class="icon">∮</span> ${this.name}</h3><div class="formula" id="formula">dB = μ₀I/(4π) · dl×R̂/R²</div><div class="learning-card"><strong>Experimento guiado · Biot–Savart</strong>Divida o condutor em elementos de corrente e some suas contribuições.<em>Compare a integral numérica com a solução fechada da geometria.</em></div>
<div class="control"><label>Condutor</label><select id="geometry"><option value="wire">Fio retilíneo finito</option><option value="loop">Espira circular</option><option value="square">Espira quadrada — centro</option></select></div>
<div class="control"><label>Corrente I (A) <span class="val" id="iV">3.0</span></label><input id="current" type="range" min="-10" max="10" step="0.5" value="3"></div><div class="control"><label><span id="sizeLabel">Comprimento L (cm)</span><span class="val" id="sizeV">20</span></label><input id="size" type="range" min="5" max="50" value="20"></div><div class="control" id="distanceControl"><label>Distância a (cm) <span class="val" id="distanceV">10</span></label><input id="distance" type="range" min="2" max="40" value="10"></div><div class="control"><label>Segmentos <span class="val" id="elementsV">40</span></label><input id="elements" type="range" min="4" max="200" step="4" value="40"></div><div class="control"><label>Mostrar elementos dl</label><label class="toggle"><input id="showElements" type="checkbox" checked><span class="track"></span></label></div>
${this.measurementPanel("Integral de Biot–Savart",[["B numérico","—"],["B analítico","—"],["Erro relativo","—"],["Sentido","—"],["Resolução","—"]])}`;
		for(const [id,value] of [["geometry",this.geometry],["current",this.current],["size",this.size],["distance",this.distance],["elements",this.elements]])el.querySelector(`#${id}`).value=String(value);el.querySelector("#showElements").checked=this.showElements;const update=()=>{const square=this.geometry==="square";el.querySelector("#sizeLabel").textContent=this.geometry==="wire"?"Comprimento L (cm)":square?"Lado s (cm)":"Raio R (cm)";el.querySelector("#distanceControl").hidden=square};update();el.querySelector("#geometry").onchange=e=>{this.geometry=e.target.value;update()};for(const [id,label] of [["current","iV"],["size","sizeV"],["distance","distanceV"],["elements","elementsV"]])el.querySelector(`#${id}`).oninput=e=>{this[id]=+e.target.value;el.querySelector(`#${label}`).textContent=id==="current"?this[id].toFixed(1):String(this[id])};el.querySelector("#showElements").onchange=e=>this.showElements=e.target.checked;
	}
	calculate(){const I=this.current,n=this.elements,s=this.size/100,a=this.distance/100,k=MU0*I/(4*PI);if(this.geometry==="wire"){const dx=s/n;let B=0;for(let i=0;i<n;i++){const x=-s/2+(i+.5)*dx,r2=x*x+a*a;B+=k*a*dx/(r2*sqrt(r2))}return {numeric:B,analytic:MU0*I*s/(4*PI*a*sqrt(a*a+(s/2)**2))}}
		if(this.geometry==="loop"){const dl=2*PI*s/n;let B=0;for(let i=0;i<n;i++){const r2=s*s+a*a;B+=k*dl*s/(r2*sqrt(r2))}return {numeric:B,analytic:MU0*I*s*s/(2*(s*s+a*a)**1.5)}}
		const perSide=max(1,Math.floor(n/4)),half=s/2,dl=s/perSide;let B=0;for(let side=0;side<4;side++)for(let i=0;i<perSide;i++){const u=-half+(i+.5)*dl,x=side<2?(side===0?u:-u):(side===2?-half:half),y=side<2?(side===0?-half:half):(side===2?-u:u),r2=x*x+y*y;B+=k*dl*half/(r2*sqrt(r2))}return {numeric:B,analytic:2*sqrt(2)*MU0*I/(PI*s)}}
	render(c){if(W<2||H<2)return;c.fillStyle="#080d17";c.fillRect(0,0,W,H);const result=this.calculate(),cx=W*.5,cy=H*.55,extent=min(W*.28,H*.27,190),n=min(this.elements,100);c.strokeStyle="#fbbf24";c.lineWidth=5;
		if(this.geometry==="wire"){c.beginPath();c.moveTo(cx-extent,cy);c.lineTo(cx+extent,cy);c.stroke();if(this.showElements)for(let i=0;i<n;i++)this.dot(c,cx-extent+(i+.5)*2*extent/n,cy);const py=cy-min(190,55+this.distance*3);this.probe(c,cx,py)}else if(this.geometry==="loop"){c.beginPath();c.ellipse(cx,cy,extent,extent*.34,0,0,2*PI);c.stroke();if(this.showElements)for(let i=0;i<n;i++){const t=2*PI*i/n;this.dot(c,cx+extent*cos(t),cy+extent*.34*sin(t))}this.probe(c,cx,cy-min(190,55+this.distance*3))}else{c.strokeRect(cx-extent,cy-extent*.65,extent*2,extent*1.3);if(this.showElements)for(let i=0;i<n;i++){const u=i/n*4;let x,y;if(u<1){x=cx-extent+2*extent*u;y=cy-extent*.65}else if(u<2){x=cx+extent;y=cy-extent*.65+1.3*extent*(u-1)}else if(u<3){x=cx+extent-2*extent*(u-2);y=cy+extent*.65}else{x=cx-extent;y=cy+extent*.65-1.3*extent*(u-3)}this.dot(c,x,y)}this.probe(c,cx,cy)}
		const error=abs(result.analytic)>1e-30?abs(result.numeric-result.analytic)/abs(result.analytic)*100:0,direction=result.numeric>=0?"saindo da tela ⊙":"entrando na tela ⊗";this.updateMeasurements([`${abs(result.numeric*1e6).toFixed(4)} µT`,`${abs(result.analytic*1e6).toFixed(4)} µT`,`${error.toFixed(4)}%`,direction,`${this.elements} segmentos dl`]);c.fillStyle="rgba(7,10,18,.82)";c.beginPath();c.roundRect(16,16,280,60,9);c.fill();c.fillStyle="#cbd5e1";c.font="11px monospace";c.fillText(`I = ${this.current.toFixed(1)} A · ${this.elements} segmentos`,28,39);c.fillStyle="#94a3b8";c.fillText(`erro = ${error.toFixed(4)}%`,28,59)}
	dot(c,x,y){c.beginPath();c.arc(x,y,2,0,2*PI);c.fillStyle="#fde68a";c.fill()}
	probe(c,x,y){c.beginPath();c.arc(x,y,13,0,2*PI);c.fillStyle="#0f172a";c.fill();c.strokeStyle="#67e8f9";c.lineWidth=2;c.stroke();c.fillStyle="#cffafe";c.font="bold 17px monospace";c.textAlign="center";c.textBaseline="middle";c.fillText(this.current>=0?"⊙":"⊗",x,y);c.textAlign="start";c.textBaseline="alphabetic"}
}
